const obj=require('./logger')
const obj1=require('./util/helper')
const obj2=require('../validator/formatter')
const obj3=require('lodash')
obj.log("Kishan")
obj.welcome()
console.log(obj.url)
obj1.printDate()
obj1.printMOnth()
obj1.getBatchInfo()
obj2.trimmer("sashh df   ")
obj2.changetoLowerCase("JJJJK")
obj2.changeToUpperCase("sagdhsagj")
const array=["january","febuary","mrch","aprill","may","june","july","august",]
console.log(obj3.chunk(array,4))
console.log(obj3.tail([1,3,5,7,9,11,13,15,17,19]))
console.log(obj3.union([1,2,3],[3,4,5],[5,6,7],[7,8,9],[10,11,12]))
console.log(obj3.fromPairs([["horror","the shining"],["drama","titanic"],["thriller","shutter island"],["fantasy","pans labyrinth"]]))